### ISSUE TITLE
DraggableMarker: Tooltip direction should depend on location of Marker and Map zoom level

### ISSUE THREAD

**Issue by fre-ben** [lmachens/arkesia.gg-web#5]
Currently, when the user tries to add a node, the marker Tooltip opens to the top by default.
This causes the Form/Card to not be visible when the marker is set close to the top of the screen.

Maybe the `direction="top"` prop of the `Tooltip` component could change dependent on Map zoom level and location of Mouse.

Screenshot to clarify the issue: [Link](https://i.imgur.com/BEzw4hY.jpeg)

**Comment by lmachens** [comment]
This issue will be worst if we add more fields to the form.
Maybe we can move the form to a separated area instead of the tooltip to solve this issue.

In Aeternum Map, the form is not part of a tooltip.

![image](https://user-images.githubusercontent.com/10058950/154838811-955795af-113d-491c-8c85-829e97d632ae.png)

I think a Dialog could be useful:
https://mantine.dev/core/dialog/
